apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neppi-api-folder-claim
  labels:
    app: neppi-strapi-desarrollo-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
