FROM node:14.15
RUN apt-get install ssh
RUN systemctl ssh start
RUN systemctl ssh enable
RUN service ssh status
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY ../package*.json ./
USER node
RUN npm install
ENV ENVIROMENT_ONLINE=true
ENV NODE_ENV=production
COPY --chown=node:node ../ .
RUN npm run build
CMD [ "npm", "run" ,"start" ]
