FROM node:14.15
RUN echo 'root:25448132' | chpasswd
RUN apt-get update && apt-get install -y openssh-server
COPY ssh/sshd_config /etc/ssh/sshd_config
RUN service ssh start 
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package*.json ./
USER node
RUN npm install
COPY --chown=node:node . .
ENV ENVIROMENT_ONLINE=true
ENV NODE_ENV=development
EXPOSE 2220
EXPOSE 1337
RUN npm run build
USER root
CMD service ssh restart && npm run develop 
