apiVersion: v1
kind: Service
metadata:
  name: neppi-strapi-desarrollo-cluster-ip
  labels:
    name: neppi-strapi-desarrollo-deploy
    app: neppi-strapi-desarrollo-app
spec:
  selector:
    app: neppi-strapi-desarrollo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337 