apiVersion: v1
kind: Service
metadata:
  name: neppi-strapi-desarrollo-node-port
  labels:
    name: neppi-strapi-desarrollo-deploy
    app: neppi-strapi-desarrollo-app
spec:
  type: NodePort
  selector:
    app: neppi-strapi-desarrollo-app
  ports:
    - protocol: TCP
      port: 1337
      nodePort: 31337
