apiVersion: v1
kind: Service
metadata:
  name: neppi-strapi-desarrollo-load-balancer
  labels:
    name: neppi-strapi-desarrollo-deploy
    app: neppi-strapi-desarrollo-app
spec:
  type: LoadBalancer
  selector:
    app: neppi-strapi-desarrollo-app
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 80
      name: http
